//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTour()
        {
            this.InformationBooks = new HashSet<InformationBook>();
        }
    
        public int Id { get; set; }
        public int TourId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int TypePay { get; set; }
        public int TypeBill { get; set; }
        public System.DateTime BookDate { get; set; }
        public System.DateTime ModDate { get; set; }
        public int Status { get; set; }
        public string Token { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal vpc_Amount { get; set; }
        public string vpc_TransactionNo { get; set; }
        public decimal ExchangeRates { get; set; }
        public int TicketsVenuesType { get; set; }
        public string TicketsVenuesAddress { get; set; }
    
        public virtual Tour Tour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformationBook> InformationBooks { get; set; }
    }
}
