//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Classes = new HashSet<Class>();
            this.Grades = new HashSet<Grade>();
        }
    
        public int IDCourse { get; set; }
        public string CMID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public string Dates { get; set; }
        public Nullable<int> Credits { get; set; }
        public Nullable<int> Days { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> BTime { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ETime { get; set; }
        public string Location { get; set; }
        public string FID { get; set; }
        public string CLID { get; set; }
        public string Title { get; set; }
    
        public virtual asp_User asp_User { get; set; }
        public virtual asp_User asp_User1 { get; set; }
        public virtual asp_User asp_User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }
    }
}
