//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForMe
    {
        public int Id { get; set; }
        public string SumaryInfo { get; set; }
        public string ContentInfo { get; set; }
        public string SumaryService { get; set; }
        public string ContentService { get; set; }
        public string SumaryAdmissions { get; set; }
        public string ContentAdmissions { get; set; }
    }
}
