//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiThieuChung
    {
        public int Id { get; set; }
        public string SumaryLocation { get; set; }
        public string ContentLocation { get; set; }
        public string SumaryInfo { get; set; }
        public string ContentInfo { get; set; }
        public string SumaryExp { get; set; }
        public string ContentExp { get; set; }
    }
}
