//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string KeyWord { get; set; }
        public string Sumary { get; set; }
        public string Content { get; set; }
    }
}
