//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatBaStationEntities : DbContext
    {
        public CatBaStationEntities()
            : base("name=CatBaStationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asp_Group> asp_Group { get; set; }
        public virtual DbSet<asp_Role> asp_Role { get; set; }
        public virtual DbSet<asp_User> asp_User { get; set; }
        public virtual DbSet<BookTour> BookTours { get; set; }
        public virtual DbSet<CategoriOther> CategoriOthers { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<ForMe> ForMes { get; set; }
        public virtual DbSet<GioiThieuChung> GioiThieuChungs { get; set; }
        public virtual DbSet<Help> Helps { get; set; }
        public virtual DbSet<InformationBook> InformationBooks { get; set; }
        public virtual DbSet<New> News { get; set; }
        public virtual DbSet<OderTour> OderTours { get; set; }
        public virtual DbSet<Phonto> Phontoes { get; set; }
        public virtual DbSet<PhotoForTour> PhotoForTours { get; set; }
        public virtual DbSet<SceduTour> SceduTours { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SlideBaner> SlideBaners { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
    }
}
