//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class New
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string KeyWord { get; set; }
        public string img { get; set; }
        public string Sumary { get; set; }
        public string Content { get; set; }
        public string link { get; set; }
        public string by { get; set; }
        public System.DateTime ModTime { get; set; }
        public bool isHome { get; set; }
    }
}
