//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoForTour
    {
        public int Id { get; set; }
        public int TourId { get; set; }
        public string Txt1 { get; set; }
        public string Txt2 { get; set; }
        public string Img { get; set; }
        public string Link { get; set; }
        public int Oder { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
