//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ID { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> Studentcount { get; set; }
        public string StatisticalData { get; set; }
        public string GradeDistributionData { get; set; }
        public Nullable<int> Status { get; set; }
        public string CLID { get; set; }
        public string CMID { get; set; }
        public string PVCID { get; set; }
        public string DLTID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Comment { get; set; }
    
        public virtual asp_User asp_User { get; set; }
        public virtual asp_User asp_User1 { get; set; }
        public virtual asp_User asp_User2 { get; set; }
        public virtual asp_User asp_User3 { get; set; }
    }
}
