//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCMV5.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.BookTours = new HashSet<BookTour>();
            this.OderTours = new HashSet<OderTour>();
            this.PhotoForTours = new HashSet<PhotoForTour>();
            this.SceduTours = new HashSet<SceduTour>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string KeyWord { get; set; }
        public string Desctiption { get; set; }
        public string Note { get; set; }
        public string img { get; set; }
        public int Rate { get; set; }
        public decimal Pice { get; set; }
        public decimal Pice2 { get; set; }
        public decimal Pice3 { get; set; }
        public string Has { get; set; }
        public string Need { get; set; }
        public System.DateTime ModTime { get; set; }
        public bool isHome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookTour> BookTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OderTour> OderTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoForTour> PhotoForTours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SceduTour> SceduTours { get; set; }
    }
}
